/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatePromptRouteImport } from './routes/create/prompt'
import { Route as CreateMusicRouteImport } from './routes/create/music'
import { Route as CreateGeneratingRouteImport } from './routes/create/generating'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePromptRoute = CreatePromptRouteImport.update({
  id: '/create/prompt',
  path: '/create/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMusicRoute = CreateMusicRouteImport.update({
  id: '/create/music',
  path: '/create/music',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGeneratingRoute = CreateGeneratingRouteImport.update({
  id: '/create/generating',
  path: '/create/generating',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/music': typeof CreateMusicRoute
  '/create/prompt': typeof CreatePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/music': typeof CreateMusicRoute
  '/create/prompt': typeof CreatePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/music': typeof CreateMusicRoute
  '/create/prompt': typeof CreatePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/create/generating'
    | '/create/music'
    | '/create/prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/create/generating'
    | '/create/music'
    | '/create/prompt'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/create/generating'
    | '/create/music'
    | '/create/prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CreateGeneratingRoute: typeof CreateGeneratingRoute
  CreateMusicRoute: typeof CreateMusicRoute
  CreatePromptRoute: typeof CreatePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/prompt': {
      id: '/create/prompt'
      path: '/create/prompt'
      fullPath: '/create/prompt'
      preLoaderRoute: typeof CreatePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/music': {
      id: '/create/music'
      path: '/create/music'
      fullPath: '/create/music'
      preLoaderRoute: typeof CreateMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/generating': {
      id: '/create/generating'
      path: '/create/generating'
      fullPath: '/create/generating'
      preLoaderRoute: typeof CreateGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CreateGeneratingRoute: CreateGeneratingRoute,
  CreateMusicRoute: CreateMusicRoute,
  CreatePromptRoute: CreatePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
